/**
 * constants.js — App-wide constants
 *
 * Centralizes role names, status values, and other magic strings
 * so they can be imported instead of hardcoded throughout the app.
 */

const ROLES = {
  CLIENT: "CLIENT",
  VENUE_MANAGER: "VENUE_MANAGER",
  SYSTEM_ADMIN: "SYSTEM_ADMIN",
};

const RESERVATION_STATUS = {
  PRELIMINARY_SUBMITTED: "PRELIMINARY_SUBMITTED",
  UNDER_REVIEW: "UNDER_REVIEW",
  PENCIL_BOOKED_DRAFT: "PENCIL_BOOKED_DRAFT",
  RETURNED_FOR_COMPLETION: "RETURNED_FOR_COMPLETION",
  EXPIRED_AUTO_REJECTED: "EXPIRED_AUTO_REJECTED",
  PAYMENT_PENDING: "PAYMENT_PENDING",
  PAYMENT_OVERDUE: "PAYMENT_OVERDUE",
  BOOKED_CONFIRMED: "BOOKED_CONFIRMED",
  REJECTED: "REJECTED",
  CANCELLED: "CANCELLED",
  BLOCKED: "BLOCKED",
};

const VM_REQUEST_STATUS = {
  PENDING_REVIEW: "PENDING_REVIEW",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
};

module.exports = {
  ROLES,
  RESERVATION_STATUS,
  VM_REQUEST_STATUS,
};
